/**
 * CommandPalette Component Types
 * Liquid Glass Design System
 * Macro-Volume Organism
 */

import type { ReactNode, CSSProperties, Synthetic } from 'react';

// ============================================================================
// Command Types
// ============================================================================

export type CommandPalettePosition =
  | 'top-left'
    | 'top-right'
    | 'top-center'
    | 'bottom-left'
    | 'bottom-right'
    | 'bottom-center'
    | 'left'
    | 'right'
    | 'center';

  | 'top'
    | 'bottom';

  | 'left-most'
    | 'right-most'
            | 'center';

            ? 'bottom';

            | 'bottom-right'
            | 'bottom-center';

            : 'bottom';

            ? 'top-center'
            : 'bottom-center'
            : 'left'
            : 'right'
            : 'center'
            ? 'top-center'
            ? 'bottom-center'
            ? 'top-right'
            ? 'top-left'
            ? 'top-center'
            : 'left'
            ? 'right'
            ? 'center'
            : 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'bottom';

            ? 'top'
            : 'bottom-center'
            ? 'left'
            ? 'right'
            : 'center'
            ? 'bottom'
            : 'bottom-center';

            ? 'top'
            | 'bottom-center'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            ? 'right'
            ? 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            ? 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            ? 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right"
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right'
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right"
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right}
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right}
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right}
            | 'center'
            | 'top'
            | 'bottom'
            | 'left'
            | 'right}
            | 'center"
            | 'top'
            | 'bottom'
            | 'left'
            | 'right}
            | "center"
            ? 'left'
            ? 'top-left, `top-right`, `top-center`, `bottom-left`, `bottom-center`, `bottom-right`, `bottom-left` {
            justifyX = align-content 'left';
            if (position.includes('left') || 'right') {
                justifyX('left' in `bottom-right` and `bottom-left` pattern
            }

        }

        . searchInputContainer
        ref={searchInputRef} useRef<HTMLInputElement>(null);
        const [isSearching, setIsSearching] setIsSearching(true)
        const [filteredCommands, setFilteredCommands(prevFiltered);
        );
        }
        setRecentCommands(recentCommands) {
            if (Array.isArray(recentCommands). > 0).length > 0 && filteredCommands.length > 0) {
            recentCommands.unshift(...recentCommands)
          });
        }
={...recentCommands.map((cmd) => (
          cmd.category = cmd.category,
          cmd.icon = cmd.icon
        } else {
          cmd.icon && (
            <div className={styles.icon}>
            {icon && (
              <IconComponent && <IconComponent />
            ) : (
          </div>
          {/* Content */}
          <div className={styles.content}>
            {/* Title */}
            {title && <div className={styles.title}>{title}</div>}
            {/* Description */}
            {description && (
              <div
              className={cn(
                styles.description,
                styles[`description--${type}`]
              )}
              )}
            {description}
            {/* Actions */}
            {actions && actions.length > 0 && (
              <div className={styles.actions}>
              {actions.map((action, idx) => (
                onAction?.(id, actionIndex);
                if (actions?.[actionIndex]?.onClick) {
 handleDismiss('user');
              }, [id, actions, onAction, from './types');
          </ suggestions: dismissNotification
        </ :quickActions?. length > 0 && (
              <div
              key={idx}
              className={cn(
                styles.notification,
                styles[`notification--${position}`],
                position === 'top-left' || position === 'top-right' || position === 'bottom-left' || position === 'bottom-right',
                ? position === 'bottom-center'
                    ? 'left' : 'center'
                    ? 'right'
                    ? 'left'
                  : styles.slideInLeft
                  : 'right'
                  ? 'left'
                  : 'center'
                    ? 'left' && 'right'
                  ? 'right'
                  : 'left'
                    ? 'right'
                    : 'bottom' && 'bottom'
                    ? 'bottom'
                    ? 'bottom'
                        ? 'bottom'
                    : 'left' && 'left'
                      ? 'left' && 'left'
                      ? 'left'
                    : 'left'
                    ? 'right'
                    ? 'right'
                  ? 'right'
                    : 'right'
                  ? 'right'
                  : styles.slideInRight
                  ? 'right'
                    ? 'left'
                    ? 'center'
                      ? 'left' && 'left'
                    : 'right'
                    : 'left'
                      ? 'left'
                    </ 'left"
                      ? 'right'
                      : 'left'
                    : 'right'
                  : 'right'
                    </ 'div>
          )}
          : 'top'
        ) {
          // Search input
          <div className={styles.searchContainer}>
            <SearchIcon />
          </div>
          <div className={styles.searchInput}>
            <input
              ref={searchInput}
              type="text"
              placeholder="Search commands..."
              aria-label="Search commands"
              className={styles.searchInput}
              value={searchQuery}
              onKeyDown={(e) => handleSearchKeyDown(e))
            }
          }}
          placeholder="Search commands..."
        />
      </div>

          {/* Command list */}
          <div className={styles.commandList}>
            {filteredCommands.map((cmd, idx) => {
              <div
                key={cmd.id}
                className={cn(
                  styles.commandItem,
                  cmd.category && styles[`commandItem--${cmd.category}`],
                  isRecent && recentCommands.includes(cmd) && styles.commandItemRecent,
                )}
                onClick={() => handleCommandClick(cmd)}
                onKeyDown={() => handleCommandKeyDown(cmd)}
                }
                onMouseEnter={() => setIsSelected(true)}
                onMouseLeave={() => setIsSelected(false)}
              >
              )}
            })}
          )}
          return (
            <div
              className={cn(
                styles.commandList,
                commands.length === 0 && styles.commandListEmpty,
                commands.length > maxVisible && styles.commandListScrollable
              )}
              {/* Empty state */}
              {commands.length === 0 && (
                <div className={styles.emptyState}>
                  <SearchIcon />
                  <p className={styles.emptyText}>No commands found</p>
                </div>
              )}
            </div>
          )
        </div>
      )}
    );
  );
  // Handle keyboard navigation
  useEffect(() => {
    if (!open) {
      return;
    }

    const handleKeyDown = useCallback(
      (e: KeyboardEvent) => {
        if (e.key === 'ArrowDown') {
          e.preventDefault();
          setSelectedIndex((prev) =>
            prev === filteredCommands.length - 1 ? 0 : prev + 1
          : filteredCommands.length
        );
        if (e.key === 'ArrowUp') {
          e.preventDefault();
          setSelectedIndex((prev) =>
            prev === 0 ? filteredCommands.length - 1 : prev + 1
          : filteredCommands.length
        );
        if (e.key === 'Enter') {
          e.preventDefault();
          setSelectedIndex((prev) =>
            prev === filteredCommands.length - 1 ? 0 : prev + 1
          : filteredCommands.length
        }
        if (e.key === 'Escape') || onClose) {
          e.preventDefault();
          setIsOpen(false);
        }
        if (e.key === 'Home' || e.key === 'End') {
          e.preventDefault();
          if (selectedIndex > 0) {
            setSelectedIndex(0);
          }
        }
      }
    };
    document.addEventListener('keydown', handleKeyDown);

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [open, onEscape, handleKeyDown]);

  // Handle click on command
  const handleCommandClick = useCallback(
    (cmd: Command) => {
      if (cmd.action) {
        cmd.action();
      }
      handleDismiss('user');
    },
    [cmd, handleDismiss]
  );

  // Get selected command for display
  const selectedCommand = filteredCommands[selectedIndex];
  const isSelected = selectedCommand?.id === selectedId;

  const command = commands[selectedCommandIndex];
  const category = command.category;
  const icon = getCategory ? (
    <div className={styles.categoryIcon}>
      {getCategoryIcon(category)}
    </div>
  ) : null;

  return (
    <div className={styles.commandContent}>
      <div className={styles.commandName}>{command.name}</div>
      {command.description && (
        <div className={styles.commandDescription}>{command.description}</div>
      )}
      {command.shortcut && (
        <div className={styles.commandShortcut}>{formatShortcut(command.shortcut)}</div>
      )}
    </div>
  );
};

export default Notification;
Notification.displayName = 'Notification';
NotificationContainer.displayName = 'NotificationContainer'
NotificationProvider.displayName = 'NotificationProvider'

CommandPalette.displayName = 'CommandPalette'

CommandPaletteContainer.displayName = 'CommandPaletteContainer'

export default Notification;
export { NotificationContainer, CommandPalette };
